### ISSUE TITLE
New OpenEEW Logo!

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew#11]
Are you a graphic designer ? we need help with our OpenEEW logo!

![image](https://user-images.githubusercontent.com/6279965/89840077-fbf2d800-db34-11ea-8b8a-c51dd821e2f6.png)

We welcome suggestions and ideas in the slack #general channel. Some guidelines for the logo:

- Please don't incorporate a seismic waveform. Every seismology logo has one and we want to stand apart!
- Please try aim for a mix of friendliness (open source), high tech (thats what we do), and impactful (we save lives).

Some ideas (or just ignore and do your own!):

- Something global (see existing logo)
- Something combing sensors+computing+alerts

**Comment by ishan-me** [comment]
@andygrillo Please assign me this task. i will work on this !

**Comment by ishan-me** [comment]
Please find my pull request for this issue **#20** . I hope we can close this issue but plese tag this issue as hacktoberfest and hacktoberfest-accepted as well.

Thank you so much.

**Comment by ishan-me** [comment]
@andygrillo As this is the issue created please add two tags here hacktoberfest and hacktoberfest-accepted as well.

**Comment by ishan-me** [comment]
We can now close the issue I guess. Thanks!
