### ISSUE TITLE
Question: community device attached to siren via a relay

### ISSUE THREAD

**Issue by nobicycle** [openeew/openeew#27]
Hello. Rather than every home owning a device (too expensive in Indonesia) I am interested in a community device that could alert people by siren, provided the openeew could activate a relay.  Possible? Ideas? 

BTW I went to openeew on Slack as recommended but found I was talking to myself, so I came back to Github.

> Wondering who can read your recent message? This channel is open to all members of your workspace, so your message might be seen by any of your teammates.

**Comment by andygrillo** [comment]
Hello @nobicycle , Slack is a realtime messaging system so dont expect everyone to be available 24hrs.

**Comment by nobicycle** [comment]
thanks
