### ISSUE TITLE
Improve react-native app

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew#7]
Add better audio alert on push notification, 
Clearer instructions for setting up,
Language in english,

**Comment by marcelorubim** [comment]
I would like to help with this one.

**Comment by andygrillo** [comment]
great! if you look at this issue: https://github.com/openeew/openeew-app-reactnative/issues/13 we are considering starting something a bit cleaner.

At its most basic, the app we need simply receives push notifications and makes sound/graphics to alert user.

It does need some additional logic (we can create another issue for this) which works out the users location and calcs distance to earthquake. Based on this we have a formala that works out expected shaking for the user.
